POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlciIsImlkIjoiNjg3ZDI4MzlkOTYyNGNkNmVjMTE5ZDI5IiwiaWF0IjoxNzUzMDM3NjcyLCJleHAiOjE3NTMwNDEyNzJ9.7TpVB8O8KU_M0UDF4JUgVMrj61Jgw2Qitc5PrL9n9u8

{
  "title": "Bloggo",
  "author": "Blogger",
  "url": "https://blog.com",
  "likes": 10,
  "userId": "687d2839d9624cd6ec119d29"
}